import { GeistSans } from "geist/font/sans";
import Head from "next/head";
import { type AppType } from "next/app";
import SignIn from "./signin";
import axios from "axios";
import { useEffect, useState } from "react";
import Leftbar from "~/components/Leftbar";
import RightPart from "~/components/RightPart";
import useSession from "~/hooks/useSession";

import "~/styles/globals.css";

const MyApp: AppType = ({ Component, pageProps }) => {
  const session = useSession();

  const [tweets, setTweets] = useState([]);
  const [premium, setPremium] = useState<any>(null);

  const fetchTweets = async () => {
    await axios.get("/api/tweet").then((res) => setTweets(res.data));
  };

  const fetchUserPremium = async () => {
    await axios
      .get(`/api/getUserPremium?userId=${session?.user.id}`)
      .then((res) => setPremium(res.data));
  };

  useEffect(() => {
    fetchTweets();
    fetchUserPremium();
  }, []);

  return (
    <>
      <Head>
        <title>X (Twitter) | Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="icon"
          href="https://img.freepik.com/free-vector/new-2023-twitter-logo-x-icon-design_1017-45418.jpg?size=338&ext=jpg&ga=GA1.1.1141335507.1719187200&semt=ais_user"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      {session ? (
        <div className="flex min-h-screen px-24">
          <div className="w-[18%]">
            <Leftbar
              premium={premium && premium[0]?.premium}
              session={session}
              fetchUserPremium={fetchUserPremium}
              fetchTweets={fetchTweets}
            />
          </div>

          <main
            className={`${GeistSans.className} ml-10 mr-8 max-h-screen flex-1 overflow-y-auto border-x border-[#383838]`}
          >
            <Component
              {...pageProps}
              session={session}
              tweets={tweets}
              fetchTweets={fetchTweets}
            />
          </main>

          <div className="w-[28%]">
            <RightPart
              premium={premium && premium[0]?.premium}
              session={session}
              fetchUserPremium={fetchUserPremium}
              fetchTweets={fetchTweets}
            />
          </div>
        </div>
      ) : (
        <SignIn />
      )}
    </>
  );
};

export default MyApp;
