import { GeistSans } from "geist/font/sans";
import Head from "next/head";
import { type AppType } from "next/app";
import SignIn from "./signin";

import "~/styles/globals.css";
import useSession from "~/hooks/useSession";

const MyApp: AppType = ({ Component, pageProps }) => {
  const session = useSession();

  return (
    <>
      <Head>
        <title>X (Twitter) | Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="icon"
          href="https://img.freepik.com/free-vector/new-2023-twitter-logo-x-icon-design_1017-45418.jpg?size=338&ext=jpg&ga=GA1.1.1141335507.1719187200&semt=ais_user"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={GeistSans.className}>
        {session ? <Component {...pageProps} session={session} /> : <SignIn />}
      </main>
    </>
  );
};

export default MyApp;
